/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pojlib.unity;

import java.io.IOException;

public class Library {
    public static void main(String[] args) throws IOException {

    }
}
