# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Pojlib

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "master", "QuestCraft" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21d
        local-cache: true
        link-to-sdk: true
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b
        local-cache: true
        link-to-sdk: true
    - name: Make Gradle wrapper executable and pull LFS
      run: git lfs pull | chmod +x ./gradlew
    - name: Decode keystore
      run: |
        bash -c 'base64 --decode <<< "$QCXR_KEYSTORE_BASE64" > qcxr.keystore'
      env:
        QCXR_KEYSTORE_BASE64: ${{ secrets.QCXR_KEYSTORE_BASE64 }}
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      env:
        QCXR_KEYSTORE_ALIAS: ${{ secrets.QCXR_KEYSTORE_ALIAS }}
        QCXR_KEYSTORE_PASS: ${{ secrets.QCXR_KEYSTORE_PASS }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
          name: app-debug
          path: build/outputs/aar/*
